# Generated by Django 5.2.1 on 2025-06-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('instructor', models.TextField()),
                ('available_slots', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField()),
                ('client_email', models.EmailField(max_length=254)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class')),
            ],
        ),
    ]
